version: "3.4"

services:
  bot:
    image: good-boi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile

  llm:
    image: koboldcpp
    restart: unless-stopped
    build:
      context: ./llm
      dockerfile: ./llm/Dockerfile
