services:
  good-boi:
    image: ghcr.io/rubikan/good-boi:master
    container_name: good-boi
    restart: unless-stopped
    pull_policy: always
    environment:
      GOODBOI_DISCORD_TOKEN: "[INSERT TOKEN HERE]"
      GOODBOI_ANNOUNCE_GUILDS: "[GUILD1]:[CHANNEL1],[GUILD2]:[CHANNEL2]"
      REPLICATE_API_TOKEN: "[INSERT TOKEN HERE]"
